---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Set default options and load required libraries
```{r opts, echo=T}
suppressWarnings({
    require(knitr); # needed for opts_chunk
    require(stringr);
    require(lubridate);
    require(dplyr);
    require(ggplot2);
    require(xtable);
})
opts_chunk$set(echo=T)
```

## Loading and preprocessing the data
```{r processdata}
activities <- read.csv(unz("activity.zip", "activity.csv"))
str(activities)
# Use dplyr to mutate the dataset to add a datetime field combining "date"
# and "interval"

## First create a character vector of dates
dates <- as.character(activities$date)

## Now create a character vector build from "interval" in the "hhmmss" format
## stringr::str_sub() is used for simpler RIGHT substrings
times <- paste0(str_sub(paste0("0000", activities$interval), -4), "00")
timestamps <- paste(str_sub(times, 1, 2),
                    str_sub(times, 3, 4),
                    sep=":")

## Use dplyr::mutate() and lubridate::ymd_hms() to create a "datetime"" field,
## and make "interval" a factor
activities <- activities %>%
    mutate(datetime = ymd_hms(paste(dates, times, sep=" "))) %>%
    mutate(interval = timestamps)

str(activities)
```

## What is mean total number of steps taken per day?
```{r dailysteps, results='asis'}
# Calculate daily total steps using dplyr
dailySteps <- activities %>%
    group_by(date) %>%
    summarize(ttl.steps=sum(steps, na.rm=T))

# Show in a histogram
ggplot(data=dailySteps, aes(ttl.steps)) +
    geom_histogram(fill=rgb(31, 119, 180, maxColorValue=255),
                   col="white") +
    labs(title="Histogram of Total Daily Steps") +
    labs(x="Total Steps", y="Count of Days") +
    theme_bw()

# Calculate mean and median of total daily steps and present in a small table
meanSteps <- mean(dailySteps$ttl.steps)
medianSteps <- median(dailySteps$ttl.steps)
stepsSummary <- data.frame(cbind(meanSteps, medianSteps))
names(stepsSummary) <- c("Mean of Ttl Daily Steps",
                         "Median of Ttl Daily Steps")

print(xtable(stepsSummary), type="html", include.rownames=F)
```

## What is the average daily activity pattern?
```{r intervalsteps}
# Calculate the mean number of steps by interval across all days
intervalSteps <- activities %>%
    group_by(interval) %>%
    summarize(mean.steps=mean(steps, na.rm=T))

# Plot the time series data
ggplot(data=intervalSteps, aes(x=interval, y=mean.steps, group=1)) +
    geom_line(col=rgb(255, 127, 14, maxColorValue=255)) +
    labs(title="Mean Steps by Interval") +
    labs(x="Time of Day (5 Minute Intervals)", y="Mean Steps") +
    scale_x_discrete(breaks=intervalSteps$interval[seq(1, 288, 24)])

# Calculate the time interval with the highest mean steps across all days.
maxInterval <- as.character(
    intervalSteps[which.max(intervalSteps$mean.steps),1])
```

The time interval with the highest mean steps across all days
is `r maxInterval`.

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
